import type { Metadata } from 'next';
import { Lato, Noto_Sans, Inter, Comic_Neue } from 'next/font/google';

import '@/app/globals.css';

import Link from 'next/link';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });
console.log(lato);
// const inter = Inter({ subsets: ['cyrillic'] });
const comicNeue = Comic_Neue({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s - Brand name',
    default: 'Brand name'
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <div className="flex gap-6">
          <Link href="/login">Log In</Link>
          <Link href="/book" className={comicNeue.className}>
            Book
          </Link>
          <Link href="/project/1234">Project</Link>
          <Link href="/todo">Todo</Link>
          <Link href="/initial-render">Initial render</Link>
          <Link href="/sub-render">Sub Render</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
